### ISSUE TITLE
Add book to list of available resources?

### ISSUE THREAD

**Issue by paulbjensen** [nwjs/website#11]
Hi,

I'm the author of "NW.js in action" - http://manning.com/jensen, a book that I'm currently writing.

I'd like to provide a link to the book on the website, so that people interested in NW.js will know that there are books on the subject, and consider purchasing them.

In return, we can offer a discount to those interested in reading the book via Manning's early access program (MEAP).

If there is anything else I can do to assist, please let me know.

Regards,

Paul Jensen

**Comment by paulbjensen** [comment]
Hi,

Just a friendly poke on this topic. Since writing the book is now on MEAP, and the editors at Manning wanted to know if we could offer you a discount in return for getting the book on the site?

**Comment by rogerwang** [comment]
Sure. We're working on the new site and will list books for NW including yours. Thanks for writing the book btw.

**Comment by TheJaredWilcurt** [comment]
@rogerwang What section of the site would it be under? Tutorials? Resources?

**Comment by ghostoy** [comment]
I will bring back the "Quick Start" section to the website. And put links of books and other resources at the end of the page for further reading.

**Comment by ghostoy** [comment]
@paulbjensen Will your book include the features for latest 0.13.0 release? Such as Chrome App support, content verification.

**Comment by paulbjensen** [comment]
Yep, chapter 10 (packaging for the word world) is currently being written, and will feature chrome apps

**Comment by ghostoy** [comment]
@paulbjensen Thank you.

**Comment by paulbjensen** [comment]
Closing as this is an old issue.
