### ISSUE TITLE
Why not using static site?

### ISSUE THREAD

**Issue by adzymaniac** [nwjs/website#3]
At the Dev branch, will using express for nwjs's website and documentation? Why not using just static site generator like jeykll, take a look at their templating language.

http://jekyllrb.com/docs/templates/

cc @dcohenb

**Comment by dcohenb** [comment]
Working on a static output generator.
It's just easy for me at least to work with ejs and express

**Comment by adzymaniac** [comment]
Oke, i wil follow your work.
