### ISSUE TITLE
Downloads are failing

### ISSUE THREAD

**Issue by TheJaredWilcurt** [nwjs/website#44]
@rogerwang 

All downloads on the website are failing. Reported on gitter 1 hour ago. Just confirmed.

**Comment by TheJaredWilcurt** [comment]
Mirror:

* https://npm.taobao.org/mirrors/nwjs/

**Comment by rogerwang** [comment]
This should be fixed. Please try again. Thanks.

**Comment by rogerwang** [comment]
close as it's reported working in https://github.com/nwjs/nw.js/issues/6962
