### ISSUE TITLE
Add release date to versions.json

### ISSUE THREAD

**Issue by c-schuhmann** [nwjs/website#46]
Hello, I'm currently doing a lot of research on web frameworks including NW.js and I would find it handy if the versions.json would contain a field with the respective release date.

If this would be okay for you, I could also create a pull request where the previous versions are already added, because I'm adding the release dates on my local version anyway.

**Comment by rogerwang** [comment]
Thanks. A PR would be appreciated.

**Comment by c-schuhmann** [comment]
Okay! I guess you prefer YYYY/MM/DD as format?

**Comment by rogerwang** [comment]
> I guess you prefer YYYY/MM/DD as format

That would be great.
