### ISSUE TITLE
Migrate to Vite

### ISSUE THREAD

**Issue by corydalis10** [nwjs/website#60]
@rogerwang How are you?
I saw this website and came up with an idea.
That is to migrate this website to Vite framework.
The current metalsmith based website is very outdated and no longer up to date.
Therefore, I think it would be great to migrate it to the Vite framework.
Please share your thoughts!

**Comment by rogerwang** [comment]
Yes. It would be great. Thanks.

**Comment by rivercory** [comment]
@rogerwang Then can I proceed this issue?

**Comment by rogerwang** [comment]
It would be better to describe your plan or give proposals first before jumping into the implementation.

**Comment by rivercory** [comment]
@rogerwang 1. Migrate your website to Vite. (existing project will be stored in the archived folder)
2. Once the migration is complete, your website will be up-to-date and stable.
3. After that, I'll improve the design of the website and apply the latest design trends.

**Comment by rogerwang** [comment]
It looks good to me.

**Comment by rivercory** [comment]
@rogerwang Can I proceed?

**Comment by rogerwang** [comment]
yes. it's good to start.
